DELETE FROM PROJECT_MEDIA;
DELETE FROM PROJECT_TECH;
DELETE FROM PROJECTS;
ALTER TABLE PROJECTS AUTO_INCREMENT = 1;
ALTER TABLE PROJECT_TECH AUTO_INCREMENT = 1;
ALTER TABLE PROJECT_MEDIA AUTO_INCREMENT = 1;

INSERT INTO PROJECTS (
        TITLE,
        SLUG,
        SHORT_DESCRIPTION,
        DESCRIPTION,
        CATEGORY,
        TYPE,
        ROLE,
        STATUS,
        START_DATE,
        END_DATE,
        GITHUB_URL,
        DEMO_URL,
        WEBSITE_URL,
        IMAGE_URL,
        THUMBNAIL_URL,
        IS_FEATURED,
        DISPLAY_ORDER
    )
VALUES (
        'Joseph Driedger Personal Website',
        'joseph-driedger-personal-website',
        'Personal portfolio website built with Node.js, Express, EJS, and MySQL.',
        'The portfolio site you are on now: a home for my projects, skills, and music videos. Visitors can search projects, filter them by category and technology, open a detail page with a screenshot gallery, watch music videos, and send a message through the contact form.

Built with a Node.js and Express backend, EJS templates, and a MySQL database, with a responsive front end in HTML, CSS, and JavaScript. The contact form is protected by reCAPTCHA and sends email through Resend. It runs on an AWS Lightsail server behind nginx and pm2, and GitHub Actions deploys it automatically whenever changes are pushed to main.',
        'personal',
        'website',
        'Developer',
        'in-progress',
        '2026-03-01',
        NULL,
        'https://github.com/JosephDriedger/Personal-Website',
        NULL,
        'https://joeydriedger.ca',
        '/images/projects/personal-website/01-home.webp',
        '/images/projects/personal-website/01-home-thumb.webp',
        TRUE,
        0
    ),
    (
        'Flank: Capture the Flag',
        'flank-capture-the-flag',
        'Desktop multiplayer Unity 2D strategy game adapted from a tabletop design.',
        'A turn-based tactical strategy game for two players, adapted from a tabletop design created in the Fall 2025 Game Design class. An Attacker tries to return flags to base while a Defender tries to eliminate every attacking piece. Each side moves differently, and captures are made by flanking an enemy piece from opposite sides on a hexagonal board. It supports single player against an AI, pass-and-play, LAN, and online multiplayer, and includes an interactive tutorial.

Built in Unity with C# gameplay logic and custom UI designed for strategic play. LAN games find each other through UDP broadcast discovery, and online games connect through a small Node.js matchmaking server. Installer scripts package the game for desktop, using Inno Setup on Windows and a disk image on macOS.',
        'personal',
        'game',
        'Developer',
        'completed',
        '2025-12-01',
        '2026-01-31',
        'https://github.com/JosephDriedger/flank-game',
        'https://josephdriedger.itch.io/flank',
        NULL,
        '/images/projects/flank/01-gameplay-board.webp',
        '/images/projects/flank/01-gameplay-board-thumb.webp',
        TRUE,
        1
    ),
    (
        'Echoes of the Forgotten Keep',
        'echoes-of-the-forgotten-keep',
        '3D dungeon-adventure game built on a custom C++ game engine.',
        'A 3D dungeon-crawler action game. Players fight through procedurally generated dungeon rooms with combo attacks and a dash, facing enemies that patrol, chase, and attack, while doors swing open on approach and floor switches drive puzzles. A health bar tracks damage, and knockback and brief invincibility after each hit keep combat readable.

Built on a custom C++20 game engine written from scratch rather than an off-the-shelf one. The engine has a data-oriented entity-component-system (ECS) core, an OpenGL 4.6 renderer with GLSL shaders, skeletal animation with GPU skinning, AABB collision, a scene stack for menus, and an SDL3 platform layer. 3D models and animations are loaded from GLB files with Assimp, math uses GLM, and the project builds with CMake.',
        'academic',
        'game',
        'Engine Architecture Engineer',
        'completed',
        '2026-03-01',
        '2026-04-30',
        'https://github.com/JosephDriedger/echoes-of-the-forgotten-keep',
        'https://github.com/JosephDriedger/echoes-of-the-forgotten-keep/releases/tag/v1.0.0',
        NULL,
        '/images/projects/echoes/01-dungeon.webp',
        '/images/projects/echoes/01-dungeon-thumb.webp',
        TRUE,
        2
    ),
    (
        'Call of Cthulhu',
        'call-of-cthulhu',
        'Atmospheric Unity 3D platformer with puzzles, cinematics, and custom Blender assets and VFX.',
        'Call of Cthulhu is a dark, atmospheric Lovecraftian 3D platformer. A lantern-carrying explorer picks through the ruins of a drowned city, pushing crates, turning ancient statues to unlock the way, and claiming a sword from a glowing altar, before facing Cthulhu himself from a raft in a storm. Cinematic camera moves open each scene, an on-screen prompt shows what the player can interact with, and the lantern is often the only warm light in the dark.

Built in Unity 6 with the Universal Render Pipeline and C#, using Game Creator for the character controller, Cinemachine and Timeline for cutscenes, and the Input System for controls. The crates, altar, raft, and Cthulhu''s eyes were modelled in Blender, generated by a Python script and imported as FBX to replace blockout geometry. Post-processing, dynamic lighting, and particle effects build the mood, including a script that generates the underwater dust, bubbles, wisps, and fog at runtime. The carried lantern uses two-bone IK to hold the arm in a grip pose and hangs from the hand as a damped pendulum.',
        'academic',
        'game',
        'Technical Artist',
        'completed',
        '2026-01-01',
        '2026-04-30',
        'https://github.com/JosephDriedger/Call-Of-Cthulhu',
        NULL,
        NULL,
        '/images/projects/call-of-cthulhu/01-statue-puzzle.webp',
        '/images/projects/call-of-cthulhu/01-statue-puzzle-thumb.webp',
        TRUE,
        3
    ),
    (
        'Inertia Pause',
        'inertia-pause',
        '3D Unity game built with a team, focused on assets and production polish.',
        'A 3D puzzle-action game built around a time-manipulation mechanic that lets the player pause and rewind inertia-driven objects, such as bullets frozen in flight, to solve physics puzzles. Scenarios play out in a bridge, a city center, a restaurant, and an office, with difficulty settings, a planning HUD, and a tutorial that explains the time-freeze mechanic.

Built by a team in Unity with C#. My role was sourcing and designing the assets: 3D models were created and edited in Blender, textures and UI art in Photoshop, and audio in Audacity, then integrated into the game to give the final release a cohesive aesthetic and a polished feel.',
        'academic',
        'game',
        'Asset Sourcer & Designer',
        'completed',
        '2025-09-01',
        '2025-12-31',
        'https://github.com/JosephDriedger/Inertia-Pause',
        'https://patrickng.itch.io/inertia-pause',
        NULL,
        '/images/projects/inertia-pause/01-bridge.webp',
        '/images/projects/inertia-pause/01-bridge-thumb.webp',
        TRUE,
        4
    ),
    (
        'Wayfindr Campus Navigation App',
        'wayfindr-campus-navigation-app',
        'Campus navigation web app with Mapbox GL and automated testing.',
        'A campus navigation web app that lets BCIT students find and navigate between buildings and classrooms. Users search for a room, see walking directions on an interactive map, browse a building''s floor plan and room list, sign in, and save favourite locations for quick access. Administrators can edit the map itself from a dedicated admin area.

Built on a Node.js and Express backend with EJS-rendered pages and Mapbox GL JS for the interactive maps. Firebase Authentication handles secure login and Firestore stores each user''s favourites, with the server using the Firebase Admin SDK and a node graph of the campus. An automated Jest test suite runs in a GitHub Actions CI pipeline to catch regressions early.',
        'academic',
        'app',
        'UI Developer',
        'completed',
        '2025-09-01',
        '2025-12-31',
        'https://github.com/JosephDriedger/WayFindr-Campus-Navigation-App',
        NULL,
        NULL,
        '/images/projects/wayfindr/01-directions.webp',
        '/images/projects/wayfindr/01-directions-thumb.webp',
        FALSE,
        5
    ),
    (
        'MelodiProof AI',
        'melodiproof-ai',
        'CNN model for detecting AI-generated music built with Python and TensorFlow.',
        'A desktop app that detects whether a music track is AI-generated. Load an audio file and it reports whether the track looks AI-generated or human-made, and shows the mel spectrogram it analysed.

A convolutional neural network (CNN) classifies mel spectrograms of the audio, producing a binary result with strong accuracy. It was trained on audio datasets with Python and TensorFlow and exported to ONNX for fast inference inside the app, with full training and evaluation pipelines for iterating on model performance. The interface is a Python Tkinter GUI, packaged as a Windows executable with PyInstaller and an Inno Setup installer.',
        'academic',
        'ai',
        'AI & ML Engineer',
        'completed',
        '2024-09-01',
        '2024-12-31',
        'https://github.com/JosephDriedger/MelodiProof-AI',
        'https://github.com/JosephDriedger/MelodiProof-AI/releases/tag/v1.0.0',
        NULL,
        '/images/projects/melodiproof/01-ai-detected.webp',
        '/images/projects/melodiproof/01-ai-detected-thumb.webp',
        FALSE,
        6
    ),
    (
        'UCM BCIT Website',
        'ucm-bcit-website',
        'Custom Node.js and Express.js website for a BCIT student club.',
        'The official website for University Christian Ministries at BCIT, replacing a limited generic website builder with a fully custom site. It shares club news, the mission statement, and weekly meeting details, lists affiliated organizations and core-group sign-ups, and has a contact page.

Built on a Node.js and Express backend with HTML, CSS, and JavaScript on the front end and a SQL database. Sessions are handled with express-session, and contact messages are emailed with Nodemailer.',
        'personal',
        'website',
        'Developer',
        'completed',
        '2023-05-01',
        '2023-12-31',
        'https://github.com/JosephDriedger/UCM_BCIT_Website',
        NULL,
        'https://www.ucmbcit.ca/',
        '/images/projects/ucm-bcit/01-home.webp',
        '/images/projects/ucm-bcit/01-home-thumb.webp',
        FALSE,
        7
    ),
    (
        'Abalone Game',
        'abalone-game',
        'Digital Abalone board game adaptation with AI decision-making, built in Python.',
        'A digital version of the Abalone marble-pushing strategy board game, built for a class tournament. It is fully playable and faithful to the original rules. Players choose their opponent, AI agent, starting formation, and time limits, and can watch AI agents battle each other with a live move history.

Built by a team of four in Python 3.11, with Pygame for rendering and Photoshop for custom UI assets. The AI opponents are driven by decision-making algorithms, and the game is packaged as a standalone Windows build with PyInstaller and an Inno Setup installer.',
        'academic',
        'game',
        'Gameplay Programmer',
        'completed',
        '2024-02-01',
        '2024-04-30',
        'https://github.com/JosephDriedger/Abalone-Game',
        'https://github.com/JosephDriedger/Abalone-Game/releases/tag/v1.0.0',
        NULL,
        '/images/projects/abalone/01-ai-battle.webp',
        '/images/projects/abalone/01-ai-battle-thumb.webp',
        FALSE,
        8
    ),
    (
        'Commute! App',
        'commute-app',
        'Commute-planning web app with live map directions, saved routes, a weekly schedule, and delay alerts.',
        'Commute! is a web app that helps commuters get where they are going on time. Users save their everyday routes and frequently visited places, plan trips on a weekly calendar with one-tap weekly repeats and a suggested leave-by time, and get alerts about incidents on their routes, each with a suggestion for staying on schedule. An interactive map gives directions between any two places for driving, biking, or walking, with travel time, distance, and step-by-step instructions, and any result can be saved as a route. Light and dark themes follow the device setting.

Built with a team of three students. The front end is plain HTML, CSS, and JavaScript with Bootstrap 5, and needs no framework or build step during development. Maps use Leaflet on OpenStreetMap tiles, with Nominatim for address search and the OpenStreetMap routing service for directions. Firebase Authentication handles email sign-in, and Cloud Firestore stores each user''s profile, routes, places, schedule, and alerts behind security rules that let users read and write only their own data. A small Node.js script builds the static site for Firebase Hosting, and a dependency-free Node.js server runs it locally.',
        'academic',
        'app',
        'Full Stack Developer',
        'completed',
        '2022-09-01',
        '2022-12-31',
        'https://github.com/JosephDriedger/Commute-App',
        NULL,
        'https://commuteapp.web.app/',
        '/images/projects/commute/01-landing.webp',
        '/images/projects/commute/01-landing-thumb.webp',
        FALSE,
        9
    ),
    (
        'Ecocities Industry Project',
        'ecocities-industry-project',
        'Industry-sponsored full-stack project using Next.js, Python, and MongoDB.',
        'An industry-sponsored web platform built for the BCIT Centre for Ecocities that lets stakeholders explore processed environmental footprint data. Visitors can view consumption-based emissions inventories and ecological footprint breakdowns, including how many Earths are required, for BC communities such as Metro Vancouver and Victoria, and switch between communities to compare them.

Built as a Next.js frontend backed by a MongoDB database that is populated through a Python CSV data pipeline. Automated tests validate application reliability.',
        'industry',
        'app',
        'Full-Stack Developer',
        'completed',
        '2024-09-01',
        '2024-12-31',
        NULL,
        NULL,
        'https://archetypefootprints.commons.bcit.ca/',
        '/images/projects/ecocities/01-emissions.webp',
        '/images/projects/ecocities/01-emissions-thumb.webp',
        FALSE,
        10
    ),
    (
        'Webmainland Media Project',
        'webmainland-media-project',
        'Industry-sponsored tenant-matching platform built with Python and Next.js.',
        'An industry-sponsored tenant-matching platform that connects landlords with prospective tenants based on configurable rental criteria. It shows property listings alongside their tenant matches and match history, and lets users search tenants for a listing and record feedback on each match.

A Python API handles the matching logic, while a Next.js frontend presents the property listings and dynamic search results. Listing and tenant data is stored in MySQL.',
        'industry',
        'app',
        'Full-Stack Developer',
        'completed',
        '2024-04-01',
        '2024-05-31',
        NULL,
        NULL,
        NULL,
        '/images/projects/webmainland/01-overview.webp',
        '/images/projects/webmainland/01-overview-thumb.webp',
        FALSE,
        11
    ),
    (
        'Lock-in'' Ringers Website',
        'lockin-ringers-website',
        'Website for a Canadian barbershop quartet built with Node.js, Express, and EJS.',
        'The official website for Lock-in'' Ringers, a young Canadian barbershop quartet based in British Columbia. It introduces the quartet and its members, explains the barbershop style and its four voice parts, lists the kinds of events they perform at, and lets visitors send a booking request. The vintage design is drawn from the quartet''s boater-hat logo, with animated barber-pole stripes and period signage typography, and it works on any screen size.

Built on a Node.js and Express backend with EJS layouts and partials, and hand-written CSS using custom properties, Grid, and Flexbox, with Google Fonts for the period typography. Requests are rate-limited with express-rate-limit. It runs on an AWS Lightsail server behind nginx with HTTPS from Let''s Encrypt, and GitHub Actions deploys it automatically on every push to main.',
        'personal',
        'website',
        'Developer',
        'in-progress',
        '2025-02-22',
        NULL,
        'https://github.com/JosephDriedger/Lockin-Ringers',
        NULL,
        'https://lockinringers.ca/',
        '/images/projects/lockin-ringers/01-home.webp',
        '/images/projects/lockin-ringers/01-home-thumb.webp',
        FALSE,
        12
    );

INSERT INTO PROJECT_TECH (PROJECT_ID, TECH_NAME, DISPLAY_ORDER)
VALUES
    -- 1: Joseph Driedger Personal Website
    (1, 'Node.js', 1),
    (1, 'Express.js', 2),
    (1, 'EJS', 3),
    (1, 'HTML5', 4),
    (1, 'CSS', 5),
    (1, 'JavaScript', 6),
    (1, 'MySQL', 7),
    -- 2: Flank: Capture the Flag
    (2, 'Unity', 1),
    (2, 'C#', 2),
    (2, 'Visual Studio', 3),
    -- 3: Echoes of the Forgotten Keep
    (3, 'C++', 1),
    (3, 'OpenGL', 2),
    (3, 'SDL3', 3),
    (3, 'GLM', 4),
    (3, 'Assimp', 5),
    (3, 'CMake', 6),
    -- 4: Call of Cthulhu
    (4, 'Unity', 1),
    (4, 'C#', 2),
    (4, 'Blender', 3),
    (4, 'Python', 4),
    -- 5: Inertia Pause
    (5, 'Unity', 1),
    (5, 'C#', 2),
    (5, 'Blender', 3),
    (5, 'Photoshop', 4),
    (5, 'Audacity', 5),
    -- 6: Wayfindr Campus Navigation App
    (6, 'EJS', 1),
    (6, 'CSS', 2),
    (6, 'JavaScript', 3),
    (6, 'Node.js', 4),
    (6, 'Express.js', 5),
    (6, 'Mapbox GL', 6),
    (6, 'Firebase', 7),
    (6, 'Python', 8),
    -- 7: MelodiProof AI
    (7, 'Python', 1),
    (7, 'TensorFlow', 2),
    (7, 'CNN', 3),
    -- 8: UCM BCIT Website
    (8, 'Node.js', 1),
    (8, 'Express.js', 2),
    (8, 'HTML', 3),
    (8, 'CSS', 4),
    (8, 'JavaScript', 5),
    (8, 'SQL', 6),
    (8, 'Git', 7),
    -- 9: Abalone Game
    (9, 'Python', 1),
    (9, 'Pygame', 2),
    (9, 'Photoshop', 3),
    -- 10: Commute! App
    (10, 'HTML5', 1),
    (10, 'CSS', 2),
    (10, 'JavaScript', 3),
    (10, 'Bootstrap', 4),
    (10, 'Leaflet', 5),
    (10, 'Firebase', 6),
    (10, 'Node.js', 7),
    (10, 'Figma', 8),
    -- 11: Ecocities Industry Project
    (11, 'Next.js', 1),
    (11, 'Python', 2),
    (11, 'MongoDB', 3),
    -- 12: Webmainland Media Project
    (12, 'Next.js', 1),
    (12, 'Python', 2),
    (12, 'MySQL', 3),
    -- 13: Lock-in' Ringers Website
    (13, 'Node.js', 1),
    (13, 'Express.js', 2),
    (13, 'EJS', 3),
    (13, 'HTML5', 4),
    (13, 'CSS', 5),
    (13, 'JavaScript', 6);

INSERT INTO PROJECT_MEDIA (
        PROJECT_ID,
        MEDIA_TYPE,
        TITLE,
        URL,
        THUMBNAIL_URL,
        DISPLAY_ORDER
    )
VALUES
    (1, 'image', 'Home page with featured projects', '/images/projects/personal-website/01-home.webp', '/images/projects/personal-website/01-home-thumb.webp', 1),
    (1, 'image', 'Projects page with search and technology filters', '/images/projects/personal-website/02-projects.webp', '/images/projects/personal-website/02-projects-thumb.webp', 2),
    (1, 'image', 'Project detail page with screenshot gallery', '/images/projects/personal-website/03-project-detail.webp', '/images/projects/personal-website/03-project-detail-thumb.webp', 3),
    (1, 'image', 'Music videos page', '/images/projects/personal-website/04-music-videos.webp', '/images/projects/personal-website/04-music-videos-thumb.webp', 4),
    (1, 'image', 'Contact form with reCAPTCHA', '/images/projects/personal-website/05-contact.webp', '/images/projects/personal-website/05-contact-thumb.webp', 5),
    (2, 'image', 'Gameplay: tactical hex board', '/images/projects/flank/01-gameplay-board.webp', '/images/projects/flank/01-gameplay-board-thumb.webp', 1),
    (2, 'image', 'Gameplay: selected pieces highlight every legal move', '/images/projects/flank/02-gameplay-selection.webp', '/images/projects/flank/02-gameplay-selection-thumb.webp', 2),
    (2, 'image', 'Main menu', '/images/projects/flank/03-main-menu.webp', '/images/projects/flank/03-main-menu-thumb.webp', 3),
    (2, 'image', 'Game modes', '/images/projects/flank/04-game-modes.webp', '/images/projects/flank/04-game-modes-thumb.webp', 4),
    (2, 'image', 'Single player setup', '/images/projects/flank/05-single-player-setup.webp', '/images/projects/flank/05-single-player-setup-thumb.webp', 5),
    (2, 'image', 'Built-in interactive tutorial', '/images/projects/flank/06-how-to-play.webp', '/images/projects/flank/06-how-to-play-thumb.webp', 6),
    (2, 'image', 'How to play: objective', '/images/projects/flank/07-objective.webp', '/images/projects/flank/07-objective-thumb.webp', 7),
    (2, 'image', 'How to play: movement', '/images/projects/flank/08-movement.webp', '/images/projects/flank/08-movement-thumb.webp', 8),
    (2, 'image', 'How to play: piece captures', '/images/projects/flank/09-captures.webp', '/images/projects/flank/09-captures-thumb.webp', 9),
    (2, 'image', 'How to play: special rules', '/images/projects/flank/10-special-rules.webp', '/images/projects/flank/10-special-rules-thumb.webp', 10),
    (3, 'image', 'Exploring the dungeon as skeleton enemies close in', '/images/projects/echoes/01-dungeon.webp', '/images/projects/echoes/01-dungeon-thumb.webp', 1),
    (3, 'image', 'Combat with the health HUD', '/images/projects/echoes/02-combat.webp', '/images/projects/echoes/02-combat-thumb.webp', 2),
    (3, 'image', 'Engine debug view showing collision volumes', '/images/projects/echoes/03-collision-debug.webp', '/images/projects/echoes/03-collision-debug-thumb.webp', 3),
    (3, 'image', 'Title screen', '/images/projects/echoes/04-title.webp', '/images/projects/echoes/04-title-thumb.webp', 4),
    (4, 'image', 'Turning an ancient statue, with the interaction prompt', '/images/projects/call-of-cthulhu/01-statue-puzzle.webp', '/images/projects/call-of-cthulhu/01-statue-puzzle-thumb.webp', 1),
    (4, 'image', 'The glowing altar holding the sword', '/images/projects/call-of-cthulhu/02-altar-sword.webp', '/images/projects/call-of-cthulhu/02-altar-sword-thumb.webp', 2),
    (4, 'image', 'Pushing a crate across the ruins', '/images/projects/call-of-cthulhu/03-crate-puzzle.webp', '/images/projects/call-of-cthulhu/03-crate-puzzle-thumb.webp', 3),
    (4, 'image', 'Cthulhu rises behind the raft', '/images/projects/call-of-cthulhu/04-cthulhu-rises.webp', '/images/projects/call-of-cthulhu/04-cthulhu-rises-thumb.webp', 4),
    (4, 'image', 'The explorer on the raft with the sword and lantern', '/images/projects/call-of-cthulhu/05-raft-lantern.webp', '/images/projects/call-of-cthulhu/05-raft-lantern-thumb.webp', 5),
    (4, 'image', 'Character close-up in the storm', '/images/projects/call-of-cthulhu/06-character.webp', '/images/projects/call-of-cthulhu/06-character-thumb.webp', 6),
    (5, 'image', 'Time frozen mid-shootout on the bridge level', '/images/projects/inertia-pause/01-bridge.webp', '/images/projects/inertia-pause/01-bridge-thumb.webp', 1),
    (5, 'image', 'City center scenario with bullets frozen in flight', '/images/projects/inertia-pause/02-city-center.webp', '/images/projects/inertia-pause/02-city-center-thumb.webp', 2),
    (5, 'image', 'Title screen', '/images/projects/inertia-pause/03-title.webp', '/images/projects/inertia-pause/03-title-thumb.webp', 3),
    (5, 'image', 'Tutorial explaining the time-freeze mechanic', '/images/projects/inertia-pause/04-tutorial.webp', '/images/projects/inertia-pause/04-tutorial-thumb.webp', 4),
    (5, 'image', 'Restaurant scenario on hard difficulty', '/images/projects/inertia-pause/05-restaurant.webp', '/images/projects/inertia-pause/05-restaurant-thumb.webp', 5),
    (5, 'image', 'Office scenario with the planning HUD', '/images/projects/inertia-pause/06-office.webp', '/images/projects/inertia-pause/06-office-thumb.webp', 6),
    (6, 'image', 'Walking directions between two rooms', '/images/projects/wayfindr/01-directions.webp', '/images/projects/wayfindr/01-directions-thumb.webp', 1),
    (6, 'image', 'Campus overview with every mapped building', '/images/projects/wayfindr/02-campus.webp', '/images/projects/wayfindr/02-campus-thumb.webp', 2),
    (6, 'image', 'A building''s floor plan and room list', '/images/projects/wayfindr/03-floor-plan.webp', '/images/projects/wayfindr/03-floor-plan-thumb.webp', 3),
    (6, 'image', 'Home page with room search', '/images/projects/wayfindr/04-home.webp', '/images/projects/wayfindr/04-home-thumb.webp', 4),
    (7, 'image', 'Detection flags a track as AI-generated', '/images/projects/melodiproof/01-ai-detected.webp', '/images/projects/melodiproof/01-ai-detected-thumb.webp', 1),
    (7, 'image', 'Detection clears a track as human-made', '/images/projects/melodiproof/02-human-made.webp', '/images/projects/melodiproof/02-human-made-thumb.webp', 2),
    (7, 'image', 'Mel spectrogram the CNN classifies', '/images/projects/melodiproof/03-spectrogram.webp', '/images/projects/melodiproof/03-spectrogram-thumb.webp', 3),
    (8, 'image', 'Home page hero and navigation', '/images/projects/ucm-bcit/01-home.webp', '/images/projects/ucm-bcit/01-home-thumb.webp', 1),
    (8, 'image', 'Mission statement and weekly club meetings', '/images/projects/ucm-bcit/02-club-meetings.webp', '/images/projects/ucm-bcit/02-club-meetings-thumb.webp', 2),
    (8, 'image', 'Core groups sign-up and affiliated organizations', '/images/projects/ucm-bcit/03-footer.webp', '/images/projects/ucm-bcit/03-footer-thumb.webp', 3),
    (9, 'image', 'AI agents battling mid-game, with the live move history', '/images/projects/abalone/01-ai-battle.webp', '/images/projects/abalone/01-ai-battle-thumb.webp', 1),
    (9, 'image', 'Game setup: opponent, agent, formation and time limits', '/images/projects/abalone/02-game-setup.webp', '/images/projects/abalone/02-game-setup-thumb.webp', 2),
    (10, 'image', 'Landing page', '/images/projects/commute/01-landing.webp', '/images/projects/commute/01-landing-thumb.webp', 1),
    (10, 'image', 'Map directions with travel time and distance', '/images/projects/commute/02-map-directions.webp', '/images/projects/commute/02-map-directions-thumb.webp', 2),
    (10, 'image', 'Step-by-step directions', '/images/projects/commute/03-directions-steps.webp', '/images/projects/commute/03-directions-steps-thumb.webp', 3),
    (10, 'image', 'Saved routes', '/images/projects/commute/04-routes.webp', '/images/projects/commute/04-routes-thumb.webp', 4),
    (10, 'image', 'Weekly trip schedule', '/images/projects/commute/05-schedule.webp', '/images/projects/commute/05-schedule-thumb.webp', 5),
    (10, 'image', 'Saved places', '/images/projects/commute/06-places.webp', '/images/projects/commute/06-places-thumb.webp', 6),
    (10, 'image', 'Incident alerts with suggestions', '/images/projects/commute/07-alerts.webp', '/images/projects/commute/07-alerts-thumb.webp', 7),
    (10, 'image', 'Dark theme', '/images/projects/commute/08-schedule-dark.webp', '/images/projects/commute/08-schedule-dark-thumb.webp', 8),
    (11, 'image', 'Consumption-based emissions inventory for Metro Vancouver', '/images/projects/ecocities/01-emissions.webp', '/images/projects/ecocities/01-emissions-thumb.webp', 1),
    (11, 'image', 'Ecological footprint breakdown and Earths required', '/images/projects/ecocities/02-footprint.webp', '/images/projects/ecocities/02-footprint-thumb.webp', 2),
    (11, 'image', 'Switching communities to view Victoria''s inventory', '/images/projects/ecocities/03-victoria.webp', '/images/projects/ecocities/03-victoria-thumb.webp', 3),
    (11, 'image', 'Typical transportation emissions in BC communities', '/images/projects/ecocities/04-transportation.webp', '/images/projects/ecocities/04-transportation-thumb.webp', 4),
    (11, 'image', 'About the data and project attributions', '/images/projects/ecocities/05-about.webp', '/images/projects/ecocities/05-about-thumb.webp', 5),
    (12, 'image', 'Property listings, tenant matches and match history', '/images/projects/webmainland/01-overview.webp', '/images/projects/webmainland/01-overview-thumb.webp', 1),
    (12, 'image', 'Searching tenants for a listing and recording match feedback', '/images/projects/webmainland/02-search.webp', '/images/projects/webmainland/02-search-thumb.webp', 2),
    (13, 'image', 'Home page hero framed by animated barber poles', '/images/projects/lockin-ringers/01-home.webp', '/images/projects/lockin-ringers/01-home-thumb.webp', 1),
    (13, 'image', 'What is Barbershop? section with the four voice parts', '/images/projects/lockin-ringers/02-what-is-barbershop.webp', '/images/projects/lockin-ringers/02-what-is-barbershop-thumb.webp', 2),
    (13, 'image', 'About page story and quartet facts', '/images/projects/lockin-ringers/03-our-story.webp', '/images/projects/lockin-ringers/03-our-story-thumb.webp', 3),
    (13, 'image', 'Event types the quartet performs at', '/images/projects/lockin-ringers/04-perform.webp', '/images/projects/lockin-ringers/04-perform-thumb.webp', 4),
    (13, 'image', 'Book a Show booking request form', '/images/projects/lockin-ringers/05-book-a-show.webp', '/images/projects/lockin-ringers/05-book-a-show-thumb.webp', 5);
