DELETE FROM PROJECT_MEDIA;
DELETE FROM PROJECT_TECH;
DELETE FROM PROJECTS;
ALTER TABLE PROJECTS AUTO_INCREMENT = 1;
ALTER TABLE PROJECT_TECH AUTO_INCREMENT = 1;
ALTER TABLE PROJECT_MEDIA AUTO_INCREMENT = 1;

INSERT INTO PROJECTS (
        TITLE,
        SLUG,
        SHORT_DESCRIPTION,
        DESCRIPTION,
        CATEGORY,
        TYPE,
        ROLE,
        STATUS,
        START_DATE,
        END_DATE,
        GITHUB_URL,
        DEMO_URL,
        WEBSITE_URL,
        IMAGE_URL,
        THUMBNAIL_URL,
        IS_FEATURED,
        DISPLAY_ORDER
    )
VALUES (
        'Joseph Driedger Personal Website',
        'joseph-driedger-personal-website',
        'Personal portfolio website built with Node.js, Express, EJS, and MySQL.',
        'A personal portfolio website for showcasing projects, technical skills, and professional experience. Built with a Node.js and Express backend, EJS templating, and a MySQL database. Features a responsive design with project filtering by category and technology, a contact form with reCAPTCHA protection, and dynamic project detail pages.',
        'personal',
        'website',
        'Developer',
        'in-progress',
        '2026-03-01',
        NULL,
        'https://github.com/JosephDriedger/Personal-Website',
        NULL,
        'https://joeydriedger.ca',
        '/images/projects/personal-website/01-home.webp',
        '/images/projects/personal-website/01-home-thumb.webp',
        TRUE,
        0
    ),
    (
        'Flank: Capture the Flag',
        'flank-capture-the-flag',
        'Desktop multiplayer Unity 2D strategy game adapted from a tabletop design.',
        'A desktop multiplayer strategy game adapted from a tabletop design created in the Fall 2025 Game Design class. Players compete in a turn-based capture-the-flag format, managing units and tactics on a grid-based battlefield. Built in Unity with C# gameplay logic and custom UI designed for strategic play.',
        'personal',
        'game',
        'Developer',
        'completed',
        '2025-12-01',
        '2026-01-31',
        'https://github.com/JosephDriedger/flank-game',
        NULL,
        NULL,
        '/images/projects/flank/01-gameplay-board.webp',
        '/images/projects/flank/01-gameplay-board-thumb.webp',
        TRUE,
        1
    ),
    (
        'Echoes of the Forgotten Keep',
        'echoes-of-the-forgotten-keep',
        '3D dungeon-adventure game built on a custom C++ game engine.',
        'A 3D dungeon-adventure game built on a fully custom C++ game engine. Players explore a dungeon environment rendered with OpenGL, navigating hazards and interacting with the world through systems built from scratch. The engine features an entity-component system (ECS), scene graph, collision detection, and physics, with 3D assets loaded via Assimp.',
        'academic',
        'game',
        'Engine Architecture Engineer',
        'completed',
        '2026-03-01',
        '2026-04-30',
        'https://github.com/JosephDriedger/echoes-of-the-forgotten-keep',
        'https://github.com/JosephDriedger/echoes-of-the-forgotten-keep/releases/tag/v1.0.0',
        NULL,
        '/images/projects/echoes/01-dungeon.webp',
        '/images/projects/echoes/01-dungeon-thumb.webp',
        TRUE,
        2
    ),
    (
        'Call of Cthulhu',
        'call-of-cthulhu',
        'Polished Unity 3D platformer vertical slice with custom Blender assets and VFX.',
        'A Unity 3D platformer elevated from a rough prototype into a polished vertical slice with a dark, atmospheric Lovecraftian aesthetic. Custom 3D assets modeled in Blender replace placeholder geometry throughout the game world. Post-processing effects, dynamic lighting, and particle VFX create tension and visual depth across all gameplay scenes.',
        'academic',
        'game',
        'Technical Artist',
        'completed',
        '2026-01-01',
        '2026-04-30',
        'https://github.com/JosephDriedger/Call-Of-Cthulhu',
        NULL,
        NULL,
        '/images/projects/call-of-cthulhu/01-sunken-city.webp',
        '/images/projects/call-of-cthulhu/01-sunken-city-thumb.webp',
        TRUE,
        3
    ),
    (
        'Inertia Pause',
        'inertia-pause',
        '3D Unity game built with a team, focused on assets and production polish.',
        'A 3D Unity game built as a team project featuring a time-manipulation mechanic that lets the player pause and rewind inertia-driven objects to solve physics puzzles. Custom 3D models, textures, and audio were sourced and integrated to bring a cohesive aesthetic and polished feel to the final release.',
        'academic',
        'game',
        'Asset Sourcer & Designer',
        'completed',
        '2025-09-01',
        '2025-12-31',
        'https://github.com/JosephDriedger/Inertia-Pause',
        'https://github.com/PatrickNg995/Inertia-Pause/releases/tag/v1.0.0',
        NULL,
        '/images/projects/inertia-pause/01-bridge.webp',
        '/images/projects/inertia-pause/01-bridge-thumb.webp',
        TRUE,
        4
    ),
    (
        'Wayfindr Campus Navigation App',
        'wayfindr-campus-navigation-app',
        'Campus navigation web app with Mapbox GL and automated testing.',
        'A web-based campus navigation app that lets BCIT students find and navigate between buildings and classrooms. Powered by Mapbox GL for interactive in-browser maps, with a Node.js and Express backend, EJS-rendered UI, and an automated testing suite to catch regressions early.',
        'academic',
        'app',
        'UI Developer',
        'completed',
        '2025-09-01',
        '2025-12-31',
        'https://github.com/JosephDriedger/WayFindr-Campus-Navigation-App',
        NULL,
        NULL,
        '/images/projects/wayfindr/01-directions.webp',
        '/images/projects/wayfindr/01-directions-thumb.webp',
        FALSE,
        5
    ),
    (
        'MelodiProof AI',
        'melodiproof-ai',
        'CNN model for detecting AI-generated music built with Python and TensorFlow.',
        'A machine learning classifier that detects AI-generated music in audio files. A convolutional neural network (CNN) is trained on audio datasets using Python and TensorFlow, producing a binary classification result with strong accuracy. Includes full training and evaluation pipelines for iterating on model performance.',
        'academic',
        'ai',
        'AI & ML Engineer',
        'completed',
        '2024-09-01',
        '2024-12-31',
        'https://github.com/JosephDriedger/MelodiProof-AI',
        'https://github.com/JosephDriedger/MelodiProof-AI/releases/tag/v1.0.0',
        NULL,
        '/images/projects/melodiproof/01-ai-detected.webp',
        '/images/projects/melodiproof/01-ai-detected-thumb.webp',
        FALSE,
        6
    ),
    (
        'UCM BCIT Website',
        'ucm-bcit-website',
        'Custom Node.js and Express.js website for a BCIT student club.',
        'The official website for University Christian Ministries at BCIT, replacing a limited generic website-builder with a fully custom implementation. Features club news, event information, and a contact page, built on a Node.js and Express backend with HTML, CSS, JavaScript, and a SQL database.',
        'personal',
        'website',
        'Developer',
        'completed',
        '2023-05-01',
        '2023-12-31',
        'https://github.com/JosephDriedger/UCM_BCIT_Website',
        NULL,
        'https://www.ucmbcit.ca/',
        '/images/projects/ucm-bcit/01-home.webp',
        '/images/projects/ucm-bcit/01-home-thumb.webp',
        FALSE,
        7
    ),
    (
        'Abalone Game',
        'abalone-game',
        'Digital Abalone board game adaptation with AI decision-making, built in Python.',
        'A digital adaptation of the Abalone marble-pushing strategy board game, built for a class tournament. Features a fully playable implementation with an AI opponent driven by decision-making algorithms, faithful to the original rules. Built in Python with Pygame for rendering and Photoshop for custom UI assets.',
        'academic',
        'game',
        'Gameplay Programmer',
        'completed',
        '2024-02-01',
        '2024-04-30',
        'https://github.com/JosephDriedger/Abalone-Game',
        'https://github.com/JosephDriedger/Abalone-Game/releases/tag/v1.0.0',
        NULL,
        '/images/projects/abalone/01-ai-battle.webp',
        '/images/projects/abalone/01-ai-battle-thumb.webp',
        FALSE,
        8
    ),
    (
        'Commute! App',
        'commute-app',
        'Commute-planning web app prototype using third-party APIs and Firebase.',
        'A commute-planning web app prototype that helps users map out transit routes to their destination. Integrates third-party transit APIs and uses Firebase for backend services, connected through a Node.js server layer with a clean HTML, CSS, and JavaScript frontend.',
        'academic',
        'app',
        'Full Stack Developer',
        'completed',
        '2022-09-01',
        '2022-12-31',
        'https://github.com/JosephDriedger/Commute-App',
        NULL,
        NULL,
        '/images/projects/commute/01-overview.webp',
        '/images/projects/commute/01-overview-thumb.webp',
        FALSE,
        9
    ),
    (
        'Ecocities Industry Project',
        'ecocities-industry-project',
        'Industry-sponsored full-stack project using Next.js, Python, and MongoDB.',
        'An industry-sponsored web platform built for the BCIT Centre for Ecocities, enabling stakeholders to explore and interact with processed environmental footprint data. Features a Next.js frontend backed by a MongoDB database populated through a Python CSV data pipeline, with automated tests validating application reliability.',
        'industry',
        'app',
        'Full-Stack Developer',
        'completed',
        '2024-09-01',
        '2024-12-31',
        NULL,
        NULL,
        'https://archetypefootprints.commons.bcit.ca/',
        '/images/projects/ecocities/01-emissions.webp',
        '/images/projects/ecocities/01-emissions-thumb.webp',
        FALSE,
        10
    ),
    (
        'Webmainland Media Project',
        'webmainland-media-project',
        'Industry-sponsored tenant-matching platform built with Python and Next.js.',
        'An industry-sponsored tenant-matching platform that connects landlords with prospective tenants based on configurable rental criteria. A Python API handles the matching logic while a Next.js frontend presents property listings and dynamic search results to users.',
        'industry',
        'app',
        'Full-Stack Developer',
        'completed',
        '2024-04-01',
        '2024-05-31',
        NULL,
        NULL,
        NULL,
        '/images/projects/webmainland/01-overview.webp',
        '/images/projects/webmainland/01-overview-thumb.webp',
        FALSE,
        11
    ),
    (
        'Lock-in'' Ringers Website',
        'lockin-ringers-website',
        'Website for a Canadian barbershop quartet built with Node.js, Express, and EJS.',
        'The official website for Lock-in'' Ringers, a young Canadian barbershop quartet. Built on a Node.js and Express backend with EJS layouts and partials, it introduces the quartet and its members, explains the barbershop style, and lets visitors request bookings for events. The vintage design is drawn from the quartet''s boater-hat logo, with animated barber-pole stripes, period signage typography, and a responsive layout.',
        'personal',
        'website',
        'Developer',
        'in-progress',
        '2025-02-22',
        NULL,
        'https://github.com/JosephDriedger/Lockin-Ringers',
        NULL,
        'https://lockinringers.ca/',
        '/images/projects/lockin-ringers/01-home.webp',
        '/images/projects/lockin-ringers/01-home-thumb.webp',
        FALSE,
        12
    );

INSERT INTO PROJECT_TECH (PROJECT_ID, TECH_NAME, DISPLAY_ORDER)
VALUES
    -- 1: Joseph Driedger Personal Website
    (1, 'Node.js', 1),
    (1, 'Express.js', 2),
    (1, 'EJS', 3),
    (1, 'HTML5', 4),
    (1, 'CSS', 5),
    (1, 'JavaScript', 6),
    (1, 'MySQL', 7),
    -- 2: Flank: Capture the Flag
    (2, 'Unity', 1),
    (2, 'C#', 2),
    (2, 'Visual Studio', 3),
    -- 3: Echoes of the Forgotten Keep
    (3, 'C++', 1),
    (3, 'OpenGL', 2),
    (3, 'GLFW', 3),
    (3, 'GLM', 4),
    (3, 'Assimp', 5),
    (3, 'CMake', 6),
    -- 4: Call of Cthulhu
    (4, 'Unity', 1),
    (4, 'C#', 2),
    (4, 'Blender', 3),
    -- 5: Inertia Pause
    (5, 'Unity', 1),
    (5, 'C#', 2),
    (5, 'Blender', 3),
    (5, 'Photoshop', 4),
    (5, 'Audacity', 5),
    -- 6: Wayfindr Campus Navigation App
    (6, 'EJS', 1),
    (6, 'CSS', 2),
    (6, 'JavaScript', 3),
    (6, 'Node.js', 4),
    (6, 'Express.js', 5),
    (6, 'Mapbox GL', 6),
    (6, 'Firebase', 7),
    (6, 'Python', 8),
    -- 7: MelodiProof AI
    (7, 'Python', 1),
    (7, 'TensorFlow', 2),
    (7, 'CNN', 3),
    -- 8: UCM BCIT Website
    (8, 'Node.js', 1),
    (8, 'Express.js', 2),
    (8, 'HTML', 3),
    (8, 'CSS', 4),
    (8, 'JavaScript', 5),
    (8, 'SQL', 6),
    (8, 'Git', 7),
    -- 9: Abalone Game
    (9, 'Python', 1),
    (9, 'Pygame', 2),
    (9, 'Photoshop', 3),
    -- 10: Commute! App
    (10, 'HTML5', 1),
    (10, 'CSS', 2),
    (10, 'JavaScript', 3),
    (10, 'Node.js', 4),
    (10, 'Firebase', 5),
    (10, 'Figma', 6),
    -- 11: Ecocities Industry Project
    (11, 'Next.js', 1),
    (11, 'Python', 2),
    (11, 'MongoDB', 3),
    -- 12: Webmainland Media Project
    (12, 'Next.js', 1),
    (12, 'Python', 2),
    (12, 'MySQL', 3),
    -- 13: Lock-in' Ringers Website
    (13, 'Node.js', 1),
    (13, 'Express.js', 2),
    (13, 'EJS', 3),
    (13, 'HTML5', 4),
    (13, 'CSS', 5),
    (13, 'JavaScript', 6);

INSERT INTO PROJECT_MEDIA (
        PROJECT_ID,
        MEDIA_TYPE,
        TITLE,
        URL,
        THUMBNAIL_URL,
        DISPLAY_ORDER
    )
VALUES
    (1, 'image', 'Home page with featured projects', '/images/projects/personal-website/01-home.webp', '/images/projects/personal-website/01-home-thumb.webp', 1),
    (1, 'image', 'Projects page with search and technology filters', '/images/projects/personal-website/02-projects.webp', '/images/projects/personal-website/02-projects-thumb.webp', 2),
    (1, 'image', 'Project detail page with screenshot gallery', '/images/projects/personal-website/03-project-detail.webp', '/images/projects/personal-website/03-project-detail-thumb.webp', 3),
    (1, 'image', 'Music videos page', '/images/projects/personal-website/04-music-videos.webp', '/images/projects/personal-website/04-music-videos-thumb.webp', 4),
    (1, 'image', 'Contact form with reCAPTCHA', '/images/projects/personal-website/05-contact.webp', '/images/projects/personal-website/05-contact-thumb.webp', 5),
    (2, 'image', 'Gameplay: tactical hex board', '/images/projects/flank/01-gameplay-board.webp', '/images/projects/flank/01-gameplay-board-thumb.webp', 1),
    (2, 'image', 'Gameplay: selected pieces highlight every legal move', '/images/projects/flank/02-gameplay-selection.webp', '/images/projects/flank/02-gameplay-selection-thumb.webp', 2),
    (2, 'image', 'Main menu', '/images/projects/flank/03-main-menu.webp', '/images/projects/flank/03-main-menu-thumb.webp', 3),
    (2, 'image', 'Game modes', '/images/projects/flank/04-game-modes.webp', '/images/projects/flank/04-game-modes-thumb.webp', 4),
    (2, 'image', 'Single player setup', '/images/projects/flank/05-single-player-setup.webp', '/images/projects/flank/05-single-player-setup-thumb.webp', 5),
    (2, 'image', 'Built-in interactive tutorial', '/images/projects/flank/06-how-to-play.webp', '/images/projects/flank/06-how-to-play-thumb.webp', 6),
    (2, 'image', 'How to play: objective', '/images/projects/flank/07-objective.webp', '/images/projects/flank/07-objective-thumb.webp', 7),
    (2, 'image', 'How to play: movement', '/images/projects/flank/08-movement.webp', '/images/projects/flank/08-movement-thumb.webp', 8),
    (2, 'image', 'How to play: piece captures', '/images/projects/flank/09-captures.webp', '/images/projects/flank/09-captures-thumb.webp', 9),
    (2, 'image', 'How to play: special rules', '/images/projects/flank/10-special-rules.webp', '/images/projects/flank/10-special-rules-thumb.webp', 10),
    (3, 'image', 'Exploring the dungeon as skeleton enemies close in', '/images/projects/echoes/01-dungeon.webp', '/images/projects/echoes/01-dungeon-thumb.webp', 1),
    (3, 'image', 'Combat with the health HUD', '/images/projects/echoes/02-combat.webp', '/images/projects/echoes/02-combat-thumb.webp', 2),
    (3, 'image', 'Engine debug view showing collision volumes', '/images/projects/echoes/03-collision-debug.webp', '/images/projects/echoes/03-collision-debug-thumb.webp', 3),
    (3, 'image', 'Title screen', '/images/projects/echoes/04-title.webp', '/images/projects/echoes/04-title-thumb.webp', 4),
    (4, 'image', 'Glowing spirit trail through the Sunken City', '/images/projects/call-of-cthulhu/01-sunken-city.webp', '/images/projects/call-of-cthulhu/01-sunken-city-thumb.webp', 1),
    (4, 'image', 'Lantern-lit shore in the rain', '/images/projects/call-of-cthulhu/02-lantern.webp', '/images/projects/call-of-cthulhu/02-lantern-thumb.webp', 2),
    (4, 'image', 'Custom character model and atmospheric lighting', '/images/projects/call-of-cthulhu/03-character.webp', '/images/projects/call-of-cthulhu/03-character-thumb.webp', 3),
    (4, 'image', 'Sunken City ruins', '/images/projects/call-of-cthulhu/04-ruins.webp', '/images/projects/call-of-cthulhu/04-ruins-thumb.webp', 4),
    (5, 'image', 'Time frozen mid-shootout on the bridge level', '/images/projects/inertia-pause/01-bridge.webp', '/images/projects/inertia-pause/01-bridge-thumb.webp', 1),
    (5, 'image', 'City center scenario with bullets frozen in flight', '/images/projects/inertia-pause/02-city-center.webp', '/images/projects/inertia-pause/02-city-center-thumb.webp', 2),
    (5, 'image', 'Title screen', '/images/projects/inertia-pause/03-title.webp', '/images/projects/inertia-pause/03-title-thumb.webp', 3),
    (5, 'image', 'Tutorial explaining the time-freeze mechanic', '/images/projects/inertia-pause/04-tutorial.webp', '/images/projects/inertia-pause/04-tutorial-thumb.webp', 4),
    (5, 'image', 'Restaurant scenario on hard difficulty', '/images/projects/inertia-pause/05-restaurant.webp', '/images/projects/inertia-pause/05-restaurant-thumb.webp', 5),
    (5, 'image', 'Office scenario with the planning HUD', '/images/projects/inertia-pause/06-office.webp', '/images/projects/inertia-pause/06-office-thumb.webp', 6),
    (6, 'image', 'Walking directions between two rooms', '/images/projects/wayfindr/01-directions.webp', '/images/projects/wayfindr/01-directions-thumb.webp', 1),
    (6, 'image', 'Campus overview with every mapped building', '/images/projects/wayfindr/02-campus.webp', '/images/projects/wayfindr/02-campus-thumb.webp', 2),
    (6, 'image', 'A building''s floor plan and room list', '/images/projects/wayfindr/03-floor-plan.webp', '/images/projects/wayfindr/03-floor-plan-thumb.webp', 3),
    (6, 'image', 'Home page with room search', '/images/projects/wayfindr/04-home.webp', '/images/projects/wayfindr/04-home-thumb.webp', 4),
    (7, 'image', 'Detection flags a track as AI-generated', '/images/projects/melodiproof/01-ai-detected.webp', '/images/projects/melodiproof/01-ai-detected-thumb.webp', 1),
    (7, 'image', 'Detection clears a track as human-made', '/images/projects/melodiproof/02-human-made.webp', '/images/projects/melodiproof/02-human-made-thumb.webp', 2),
    (7, 'image', 'Mel spectrogram the CNN classifies', '/images/projects/melodiproof/03-spectrogram.webp', '/images/projects/melodiproof/03-spectrogram-thumb.webp', 3),
    (8, 'image', 'Home page hero and navigation', '/images/projects/ucm-bcit/01-home.webp', '/images/projects/ucm-bcit/01-home-thumb.webp', 1),
    (8, 'image', 'Mission statement and weekly club meetings', '/images/projects/ucm-bcit/02-club-meetings.webp', '/images/projects/ucm-bcit/02-club-meetings-thumb.webp', 2),
    (8, 'image', 'Core groups sign-up and affiliated organizations', '/images/projects/ucm-bcit/03-footer.webp', '/images/projects/ucm-bcit/03-footer-thumb.webp', 3),
    (9, 'image', 'AI agents battling mid-game, with the live move history', '/images/projects/abalone/01-ai-battle.webp', '/images/projects/abalone/01-ai-battle-thumb.webp', 1),
    (9, 'image', 'Game setup: opponent, agent, formation and time limits', '/images/projects/abalone/02-game-setup.webp', '/images/projects/abalone/02-game-setup-thumb.webp', 2),
    (10, 'image', 'Landing page, map with place search, and email sign-in', '/images/projects/commute/01-overview.webp', '/images/projects/commute/01-overview-thumb.webp', 1),
    (10, 'image', 'Map search and the commuter profile', '/images/projects/commute/02-map-profile.webp', '/images/projects/commute/02-map-profile-thumb.webp', 2),
    (11, 'image', 'Consumption-based emissions inventory for Metro Vancouver', '/images/projects/ecocities/01-emissions.webp', '/images/projects/ecocities/01-emissions-thumb.webp', 1),
    (11, 'image', 'Ecological footprint breakdown and Earths required', '/images/projects/ecocities/02-footprint.webp', '/images/projects/ecocities/02-footprint-thumb.webp', 2),
    (11, 'image', 'Switching communities to view Victoria''s inventory', '/images/projects/ecocities/03-victoria.webp', '/images/projects/ecocities/03-victoria-thumb.webp', 3),
    (11, 'image', 'Typical transportation emissions in BC communities', '/images/projects/ecocities/04-transportation.webp', '/images/projects/ecocities/04-transportation-thumb.webp', 4),
    (11, 'image', 'About the data and project attributions', '/images/projects/ecocities/05-about.webp', '/images/projects/ecocities/05-about-thumb.webp', 5),
    (12, 'image', 'Property listings, tenant matches and match history', '/images/projects/webmainland/01-overview.webp', '/images/projects/webmainland/01-overview-thumb.webp', 1),
    (12, 'image', 'Searching tenants for a listing and recording match feedback', '/images/projects/webmainland/02-search.webp', '/images/projects/webmainland/02-search-thumb.webp', 2),
    (13, 'image', 'Home page hero framed by animated barber poles', '/images/projects/lockin-ringers/01-home.webp', '/images/projects/lockin-ringers/01-home-thumb.webp', 1),
    (13, 'image', 'What is Barbershop? section with the four voice parts', '/images/projects/lockin-ringers/02-what-is-barbershop.webp', '/images/projects/lockin-ringers/02-what-is-barbershop-thumb.webp', 2),
    (13, 'image', 'About page story and quartet facts', '/images/projects/lockin-ringers/03-our-story.webp', '/images/projects/lockin-ringers/03-our-story-thumb.webp', 3),
    (13, 'image', 'Event types the quartet performs at', '/images/projects/lockin-ringers/04-perform.webp', '/images/projects/lockin-ringers/04-perform-thumb.webp', 4),
    (13, 'image', 'Book a Show booking request form', '/images/projects/lockin-ringers/05-book-a-show.webp', '/images/projects/lockin-ringers/05-book-a-show-thumb.webp', 5);
