INSERT INTO PROJECTS (
        TITLE,
        SLUG,
        SHORT_DESCRIPTION,
        DESCRIPTION,
        CATEGORY,
        TYPE,
        ROLE,
        STATUS,
        START_DATE,
        END_DATE,
        GITHUB_URL,
        DEMO_URL,
        WEBSITE_URL,
        IMAGE_URL,
        THUMBNAIL_URL,
        IS_FEATURED,
        DISPLAY_ORDER
    )
VALUES (
        'Flank: Capture the Flag',
        'flank-capture-the-flag',
        'Desktop multiplayer Unity strategy game based on a tabletop design.',
        'Took a design for a tabletop game from the Fall 2025 Game Design class and turned it into a desktop game.',
        'personal',
        'game',
        'Developer',
        'completed',
        '2025-01-01',
        '2025-12-31',
        'https://github.com/JosephDriedger/flank-game',
        NULL,
        NULL,
        '/images/projects/flank.png',
        '/images/projects/flank-thumb.png',
        TRUE,
        1
    ),
    (
        'Inertia Pause',
        'inertia-pause',
        '3D puzzle action game created with a team in Unity.',
        'Worked with 4 other team members to design and create a 3D game and learned how to develop 3D games with production polish.',
        'academic',
        'game',
        'Asset Sourcer & Designer',
        'completed',
        '2025-09-01',
        '2025-12-31',
        'https://github.com/JosephDriedger/Inertia-Pause',
        NULL,
        NULL,
        '/images/projects/inertia-pause.png',
        '/images/projects/inertia-pause-thumb.png',
        TRUE,
        2
    ),
    (
        'Wayfindr Campus Navigation App',
        'wayfindr-campus-navigation-app',
        'Campus navigation prototype built with Node, Express, Firebase, and Mapbox GL.',
        'Worked with 3 other team members to develop a working concept of a navigation app that allows students to navigate between classrooms and buildings.',
        'academic',
        'app',
        'UI Developer',
        'completed',
        '2025-09-01',
        '2025-12-31',
        'https://github.com/JosephDriedger/WayFindr-Campus-Navigation-App',
        NULL,
        NULL,
        '/images/projects/wayfindr.png',
        '/images/projects/wayfindr-thumb.png',
        TRUE,
        3
    ),
    (
        'MelodiProof AI',
        'melodiproof-ai',
        'Machine learning project for detecting AI-generated music.',
        'Worked with 3 other team members to create a machine learning system to detect AI generation in music audio files.',
        'academic',
        'ai',
        'AI & ML Engineer',
        'completed',
        '2024-09-01',
        '2024-12-31',
        'https://github.com/JosephDriedger/MelodiProof-AI',
        NULL,
        NULL,
        '/images/projects/melodiproof.png',
        '/images/projects/melodiproof-thumb.png',
        TRUE,
        4
    ),
    (
        'Abalone Game',
        'abalone-game',
        'Strategy board game adaptation with gameplay AI.',
        'Worked with 3 other team members to create a computer version of Abalone for a class tournament and learned AI programming for games development.',
        'academic',
        'game',
        'Gameplay Programmer',
        'completed',
        '2024-02-01',
        '2024-04-30',
        'https://github.com/JosephDriedger/Abalone-Game',
        NULL,
        NULL,
        '/images/projects/abalone.png',
        '/images/projects/abalone-thumb.png',
        FALSE,
        5
    ),
    (
        'Commute! App',
        'commute-app',
        'Commute planning demo using APIs and Firebase.',
        'Worked with 2 other team members to create a demo version of a commute app using APIs and Node.js.',
        'academic',
        'app',
        'Full Stack Developer',
        'completed',
        '2022-09-01',
        '2022-12-31',
        'https://github.com/JosephDriedger/Commute-App',
        NULL,
        NULL,
        '/images/projects/commute.png',
        '/images/projects/commute-thumb.png',
        FALSE,
        6
    ),
    (
        'UCM BCIT Website',
        'ucm-bcit-website',
        'Custom Node-based website for a school club.',
        'Transformed a generic web-builder website into a custom Node-based website.',
        'personal',
        'website',
        'Developer',
        'completed',
        '2023-05-01',
        '2023-12-31',
        'https://github.com/JosephDriedger/UCM_BCIT_Website',
        NULL,
        'https://www.ucmbcit.ca/',
        '/images/projects/ucm-bcit.png',
        '/images/projects/ucm-bcit-thumb.png',
        FALSE,
        7
    ),
    (
        'Joseph Driedger Personal Website',
        'joseph-driedger-personal-website',
        'Personal portfolio website built with EJS and web technologies.',
        'Created a personal website using HTML5, CSS, JavaScript, and EJS.',
        'personal',
        'website',
        'Developer',
        'in-progress',
        '2026-03-01',
        NULL,
        'https://github.com/JosephDriedger/Personal-Website',
        NULL,
        'https://joeydriedger.ca',
        '/images/projects/personal-website.png',
        '/images/projects/personal-website-thumb.png',
        TRUE,
        0
    ),
    (
        'Ecocities Industry Project',
        'ecocities-industry-project',
        'Industry-sponsored full-stack project using Next.js, Python, and MongoDB.',
        'Created automated tests using Python and Next.js, implemented a data pipeline from CSV to MongoDB, and built a web page.',
        'industry',
        'app',
        'Full-Stack Developer',
        'completed',
        '2024-09-01',
        '2024-12-31',
        NULL,
        NULL,
        NULL,
        '/images/projects/ecocities.png',
        '/images/projects/ecocities-thumb.png',
        FALSE,
        8
    ),
    (
        'Webmainland Media Project',
        'webmainland-media-project',
        'Industry-sponsored tenant matching platform built with Python and Next.js.',
        'Developed a Python API to match landlords to prospective tenants and a Next.js app to display search results.',
        'industry',
        'app',
        'Full-Stack Developer',
        'completed',
        '2024-04-01',
        '2024-05-31',
        NULL,
        NULL,
        NULL,
        '/images/projects/webmainland.png',
        '/images/projects/webmainland-thumb.png',
        FALSE,
        9
    );
    
INSERT INTO PROJECT_TECH (PROJECT_ID, TECH_NAME, DISPLAY_ORDER)
VALUES (1, 'Unity', 1),
    (1, 'C#', 2),
    (1, 'Visual Studio', 3),
    (2, 'Unity', 1),
    (2, 'C#', 2),
    (2, 'Blender', 3),
    (2, 'Photoshop', 4),
    (2, 'Audacity', 5),
    (3, 'EJS', 1),
    (3, 'CSS', 2),
    (3, 'JavaScript', 3),
    (3, 'Node.js', 4),
    (3, 'Express.js', 5),
    (3, 'Mapbox GL', 6),
    (3, 'Firebase', 7),
    (3, 'Python', 8),
    (4, 'Python', 1),
    (4, 'TensorFlow', 2),
    (4, 'CNN', 3),
    (5, 'Python', 1),
    (5, 'Pygame', 2),
    (5, 'Photoshop', 3),
    (6, 'HTML5', 1),
    (6, 'CSS', 2),
    (6, 'JavaScript', 3),
    (6, 'Node.js', 4),
    (6, 'Firebase', 5),
    (6, 'Figma', 6),
    (7, 'Node.js', 1),
    (7, 'Express.js', 2),
    (7, 'HTML', 3),
    (7, 'CSS', 4),
    (7, 'JavaScript', 5),
    (7, 'SQL', 6),
    (7, 'Git', 7),
    (8, 'HTML5', 1),
    (8, 'CSS', 2),
    (8, 'JavaScript', 3),
    (8, 'EJS', 4),
    (9, 'Next.js', 1),
    (9, 'Python', 2),
    (9, 'MongoDB', 3),
    (10, 'Next.js', 1),
    (10, 'Python', 2),
    (10, 'MySQL', 3);
INSERT INTO PROJECT_MEDIA (
        PROJECT_ID,
        MEDIA_TYPE,
        TITLE,
        URL,
        THUMBNAIL_URL,
        DISPLAY_ORDER
    )
VALUES (
        1,
        'image',
        'Flank Screenshot',
        '/images/projects/flank.png',
        '/images/projects/flank-thumb.png',
        1
    ),
    (
        2,
        'image',
        'Inertia Pause Screenshot',
        '/images/projects/inertia-pause.png',
        '/images/projects/inertia-pause-thumb.png',
        1
    ),
    (
        3,
        'image',
        'Wayfindr Screenshot',
        '/images/projects/wayfindr.png',
        '/images/projects/wayfindr-thumb.png',
        1
    ),
    (
        7,
        'image',
        'UCM BCIT Homepage',
        '/images/projects/ucm-bcit.png',
        '/images/projects/ucm-bcit-thumb.png',
        1
    ),
    (
        8,
        'image',
        'Personal Website Screenshot',
        '/images/projects/personal-website.png',
        '/images/projects/personal-website-thumb.png',
        1
    );

