USE joeydrie_PERSONAL_WEBSITE;

-- Projects extracted from Joseph Driedger's resume.
-- Images and videos intentionally omitted.
-- Assumes PROJECTS and PROJECT_TECH already exist as defined in schema.sql.

INSERT INTO PROJECTS (
    TITLE,
    SLUG,
    SHORT_DESCRIPTION,
    DESCRIPTION,
    CATEGORY,
    TYPE,
    ROLE,
    STATUS,
    START_DATE,
    END_DATE,
    GITHUB_URL,
    DEMO_URL,
    WEBSITE_URL,
    IMAGE_URL,
    THUMBNAIL_URL,
    IS_FEATURED,
    DISPLAY_ORDER
)
VALUES
(
    'Joseph Driedger Personal Website',
    'joseph-driedger-personal-website',
    'Personal portfolio website built with Node.js, Express, and EJS.',
    'Developed a personal portfolio website to showcase projects, skills, and experience. Built dynamic pages using Node.js, Express, and EJS templates, and implemented responsive layouts using HTML, CSS, and JavaScript.',
    'Personal',
    'website',
    'Developer',
    'in-progress',
    '2026-03-01',
    NULL,
    'https://github.com/JosephDriedger/Personal-Website',
    NULL,
    'https://joeydriedger.ca',
    NULL,
    NULL,
    TRUE,
    1
),
(
    'Flank: Capture the Flag',
    'flank-capture-the-flag',
    'Desktop multiplayer Unity strategy game adapted from a tabletop design.',
    'Converted a tabletop capture-the-flag strategy game into a desktop multiplayer game using Unity. Implemented core gameplay mechanics and game logic using C#, and designed game systems and user interface for turn-based strategic gameplay.',
    'Personal',
    'game',
    'Developer',
    'completed',
    '2025-12-01',
    '2026-01-31',
    'https://github.com/JosephDriedger/flank-game',
    NULL,
    NULL,
    NULL,
    NULL,
    TRUE,
    2
),
(
    'UCM BCIT Website',
    'ucm-bcit-website',
    'Custom Node.js and Express.js website for a school club.',
    'Developed a custom Node.js and Express.js website to replace a generic website builder implementation. Designed and implemented the site layout and backend structure using HTML, CSS, JavaScript, and SQL, and maintained the site for the student club.',
    'Personal',
    'website',
    'Developer',
    'completed',
    '2023-05-01',
    '2023-12-31',
    'https://github.com/JosephDriedger/UCM_BCIT_Website',
    NULL,
    'https://www.ucmbcit.ca/',
    NULL,
    NULL,
    FALSE,
    3
),
(
    'Inertia Pause',
    'inertia-pause',
    '3D Unity game created with a team of five students.',
    'Collaborated with a team of five students to design and develop a 3D game using Unity. Created and integrated game assets including 3D models, textures, and audio, and contributed to gameplay design and production polish.',
    'Academic',
    'game',
    'Asset Sourcer & Designer',
    'completed',
    '2025-09-01',
    '2025-12-31',
    'https://github.com/JosephDriedger/Inertia-Pause',
    NULL,
    NULL,
    NULL,
    NULL,
    TRUE,
    4
),
(
    'Wayfindr Campus Navigation App',
    'wayfindr-campus-navigation-app',
    'Campus navigation web application with interactive building navigation.',
    'Developed UI components for a campus navigation web application using EJS, JavaScript, and CSS. Integrated Mapbox GL for interactive building navigation and implemented automated testing workflows to improve reliability.',
    'Academic',
    'app',
    'UI Developer',
    'completed',
    '2025-09-01',
    '2025-12-31',
    'https://github.com/JosephDriedger/WayFindr-Campus-Navigation-App',
    NULL,
    NULL,
    NULL,
    NULL,
    TRUE,
    5
),
(
    'MelodiProof AI',
    'melodiproof-ai',
    'Machine learning system for detecting AI-generated music.',
    'Developed a machine learning model to detect AI-generated music using convolutional neural networks. Implemented training and evaluation pipelines using Python and TensorFlow, and collaborated with a team to research and test audio-analysis approaches.',
    'Academic',
    'ai',
    'AI & ML Engineer',
    'completed',
    '2024-09-01',
    '2024-12-31',
    'https://github.com/JosephDriedger/MelodiProof-AI',
    NULL,
    NULL,
    NULL,
    NULL,
    TRUE,
    6
),
(
    'Abalone Game',
    'abalone-game',
    'Computer version of the Abalone strategy board game with gameplay AI.',
    'Collaborated with a team of four students to develop a computer version of the Abalone strategy board game. Implemented AI decision-making logic and gameplay mechanics using Python and Pygame, and designed game assets and UI components for the class tournament version.',
    'Academic',
    'game',
    'Gameplay Programmer',
    'completed',
    '2024-02-01',
    '2024-04-30',
    'https://github.com/JosephDriedger/Abalone-Game',
    NULL,
    NULL,
    NULL,
    NULL,
    FALSE,
    7
),
(
    'Commute! App',
    'commute-app',
    'Prototype commute-planning web application using APIs and Firebase.',
    'Collaborated with a team of three students to develop a prototype commute planning web application. Integrated third-party APIs and Firebase backend services using Node.js, and designed front-end interfaces using HTML, CSS, and JavaScript.',
    'Academic',
    'app',
    'Full Stack Developer',
    'completed',
    '2022-09-01',
    '2022-12-31',
    'https://github.com/JosephDriedger/Commute-App',
    NULL,
    NULL,
    NULL,
    NULL,
    FALSE,
    8
),
(
    'Ecocities Industry Project',
    'ecocities-industry-project',
    'Industry-sponsored full-stack project using Next.js, Python, and MongoDB.',
    'Developed automated testing tools using Python and Next.js to validate application functionality. Built a data pipeline to process CSV datasets and populate a MongoDB database, designed a web interface using Next.js, and collaborated with stakeholders to deploy the software.',
    'Industry',
    'app',
    'Full-Stack Developer',
    'completed',
    '2024-09-01',
    '2024-12-31',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    FALSE,
    9
),
(
    'Webmainland Media Project',
    'webmainland-media-project',
    'Industry-sponsored tenant-matching platform built with Python and Next.js.',
    'Developed a Python API to match landlords with prospective tenants based on rental criteria. Built a Next.js web application to display property listings and tenant matching results, and collaborated with remote stakeholders across multiple time zones.',
    'Industry',
    'app',
    'Full-Stack Developer',
    'completed',
    '2024-04-01',
    '2024-05-31',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    FALSE,
    10
);

INSERT INTO PROJECT_TECH (PROJECT_ID, TECH_NAME, DISPLAY_ORDER)
VALUES
(1, 'Node.js', 1),
(1, 'Express.js', 2),
(1, 'EJS', 3),
(1, 'HTML', 4),
(1, 'CSS', 5),
(1, 'JavaScript', 6),

(2, 'Unity', 1),
(2, 'C#', 2),
(2, 'Visual Studio', 3),

(3, 'Node.js', 1),
(3, 'Express.js', 2),
(3, 'HTML', 3),
(3, 'CSS', 4),
(3, 'JavaScript', 5),
(3, 'SQL', 6),

(4, 'Unity', 1),
(4, '3D Modeling', 2),
(4, 'Texturing', 3),
(4, 'Audio Integration', 4),

(5, 'EJS', 1),
(5, 'JavaScript', 2),
(5, 'CSS', 3),
(5, 'Mapbox GL', 4),
(5, 'Automated Testing', 5),

(6, 'Python', 1),
(6, 'TensorFlow', 2),
(6, 'CNN', 3),
(6, 'Machine Learning', 4),

(7, 'Python', 1),
(7, 'Pygame', 2),
(7, 'Photoshop', 3),
(7, 'AI', 4),

(8, 'HTML5', 1),
(8, 'CSS', 2),
(8, 'JavaScript', 3),
(8, 'Node.js', 4),
(8, 'Firebase', 5),
(8, 'Figma', 6),

(9, 'Next.js', 1),
(9, 'Python', 2),
(9, 'MongoDB', 3),
(9, 'Automated Testing', 4),
(9, 'Data Pipeline', 5),

(10, 'Python', 1),
(10, 'Next.js', 2),
(10, 'API Development', 3),
(10, 'Tenant Matching', 4);
