CREATE DATABASE IF NOT EXISTS joeydrie_PERSONAL_WEBSITE;
USE joeydrie_PERSONAL_WEBSITE;

DROP TABLE IF EXISTS PROJECT_MEDIA;
DROP TABLE IF EXISTS PROJECT_TECH;
DROP TABLE IF EXISTS VIDEOS;
DROP TABLE IF EXISTS PROJECTS;

CREATE TABLE PROJECTS
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    SLUG VARCHAR(255) NOT NULL UNIQUE,
    SHORT_DESCRIPTION VARCHAR(255),
    DESCRIPTION TEXT,
    CATEGORY ENUM('Personal','Academic','Industry') NOT NULL DEFAULT 'Personal',
    TYPE ENUM('Game','App','Website','AI','Other') NOT NULL DEFAULT 'App',
    ROLE VARCHAR(255),
    STATUS ENUM('Planned','In-Progress','Completed') NOT NULL DEFAULT 'Completed',
    START_DATE DATE,
    END_DATE DATE,
    GITHUB_URL VARCHAR(255),
    DEMO_URL VARCHAR(255),
    WEBSITE_URL VARCHAR(255),
    IMAGE_URL VARCHAR(255),
    THUMBNAIL_URL VARCHAR(255),
    IS_FEATURED BOOLEAN NOT NULL DEFAULT FALSE,
    DISPLAY_ORDER INT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PROJECT_TECH
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_ID INT NOT NULL,
    TECH_NAME VARCHAR(100) NOT NULL,
    DISPLAY_ORDER INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_PROJECT_TECH_PROJECT
        FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
        ON DELETE CASCADE
);

CREATE TABLE PROJECT_MEDIA
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PROJECT_ID INT NOT NULL,
    MEDIA_TYPE ENUM('Image','Video','YouTube') NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    URL VARCHAR(255) NOT NULL,
    THUMBNAIL_URL VARCHAR(255),
    DISPLAY_ORDER INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_PROJECT_MEDIA_PROJECT
        FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID)
        ON DELETE CASCADE
);

CREATE TABLE VIDEOS
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    VIDEO_ID VARCHAR(20) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

