CREATE DATABASE IF NOT EXISTS PERSONAL_WEBSITE;

USE PERSONAL_WEBSITE;

CREATE TABLE PROJECTS
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    TYPE ENUM('game','app') NOT NULL,
    GITHUB_URL VARCHAR(255),
    DEMO_URL VARCHAR(255),
    IMAGE_URL VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE VIDEOS
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    YOUTUBE_URL VARCHAR(255) NOT NULL,
    THUMBNAIL VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
