INSERT INTO VIDEOS (TITLE, VIDEO_ID) VALUES
('It''s My Song', 'glHIhSeMmTc'),
('You Are My Sunshine', 'TEbh2tURiZg'),
('Them There Eyes', '4sTn-SgnCuM'),
('In Dixieland', 'OHDIO9sB8XI'),
('Cornbread', 'pb3ZI0hCyMQ'),
('Last Night Was The End Of The World', 'OjymieXpCYE'),
('Lonely For You Am I', 'J8LilIrGLdo'),
('Go The Distance', '7QhnLsfkufM'),
('When I Leave The World Behind', 'gaYbeOE9c1I'),
('What Child Is This', 'mseKOBkOM4I'),
('Cry', 'FOCwB_fa3QU'),
('Til You Find Your Dream', 'SGKXsoHJO0M'),
('We''ll Build A Rainbow', 'jiM_uf3m3OQ'),
('Aladdin (Medley)', 'HNdq3zsF0s0'),
('Let It Go', 'G9mgU9Yrl90'),
('The Impossible Dream', 'fRP-bJvfZw0'),
('Like Leaves Will Fall', 'iUB435PfQ1I'),
('O Canada', 'tcAlWdByw5I'),
('I''ve Been Working On The Railroad (Parody)', 'ijqIuxXhG24'),
('We Wish You A Merry Christmas', 'SfmmwVRgR_g'),
('Give Me That Barbershop Style', 'Q3hwVd8tKBg'),
('Hello Mary Lou', 'u51UHwSW11g'),
('Let There Be Peace On Earth', 'soRO-1HMu6Q'),
('God Rest Ye Merry Gentlemen', '-oW-TNWJg74'),
('No One Sings Higher Than Me', '7gpw5dnPYkQ');
